name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}-destroy
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ~> 1.14

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        env:
          TF_IN_AUTOMATION: true

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan_destroy
        env:
          TF_IN_AUTOMATION: true
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_letsencrypt_email: ${{ secrets.LETSENCRYPT_EMAIL }}

      - name: Terraform Destroy
        run: terraform apply -lock=false -auto-approve tfplan_destroy
        env:
          TF_IN_AUTOMATION: true
